### ISSUE TITLE
Slack 4.0: Profile pop-up has white background with grey text, hard to read

### ISSUE THREAD

**Issue by sentoren** [elv1n/slack-dark-mojave-theme#10]
Styling appears to not be applying correctly to the profile pop-up that appears after clicking on a user's handle. Sidebar version of profile is not affected. Screenshot attached with version visible.

Troubleshooting attempted: Rolled back theme, then reapplied while Slack was closed. Issue persisted.

<img width="759" alt="Screen Shot 2019-07-24 at 9 33 41 AM" src="https://user-images.githubusercontent.com/31142550/61811500-70f25300-adf6-11e9-8fda-ec845acf6ae5.png">

**Comment by elv1n** [comment]
Thanks for the report
Fixed, reload your slack
