### ISSUE TITLE
Can't install theme on Slack Version 4.0.1 (App Store)

### ISSUE THREAD

**Issue by eyaleizenberg** [elv1n/slack-dark-mojave-theme#11]
<img width="1145" alt="Screen Shot 2019-08-13 at 8 54 50" src="https://user-images.githubusercontent.com/1061345/62918392-25edaf00-bda8-11e9-8799-769e7d0012af.png">

**Comment by eyaleizenberg** [comment]
@elv1n any chance you can take a look?

**Comment by elv1n** [comment]
@eyaleizenberg I believe the issue with access and it will work with `sudo`.
I released a new version with details about it. Please, reopen if won't help

**Comment by eyaleizenberg** [comment]
Yup it's fixed now. Thanks.
