### ISSUE TITLE
Collapsed snippet has incorrect fade

### ISSUE THREAD

**Issue by SystemDisc** [elv1n/slack-dark-mojave-theme#3]
![screen shot 2019-02-25 at 12 35 24 pm](https://user-images.githubusercontent.com/1561860/53356679-f16d6000-38f9-11e9-9069-d2e2ccd428d6.png)

**Comment by elv1n** [comment]
It was fixed 2 days ago in v0.1.16. Could you please reload the page and check it again?

**Comment by SystemDisc** [comment]
Oh, you're right. I just had to restart Slack. I'll close this issue. Thanks 😄
