### ISSUE TITLE
"All Threads" completely unstyled and "All Unreads" not fully styled

### ISSUE THREAD

**Issue by SystemDisc** [elv1n/slack-dark-mojave-theme#4]
The elements on the "All Unreads" view are not styled correctly. Here's a screenshot.

![screen shot 2019-02-27 at 1 25 14 pm](https://user-images.githubusercontent.com/1561860/53513486-54462f00-3a93-11e9-8467-021377f2478a.png)

Note: I have tried restarting Slack to pull in the latest CSS.

**Comment by SystemDisc** [comment]
All Threads is now completely unstyled. All Unreads is still missing a lot of styling (sensitive information censored with colored rectangles).

![Screen Shot 2019-03-25 at 11 16 07 AM](https://user-images.githubusercontent.com/1561860/54932000-71ceb300-4ef0-11e9-816d-6a657d0302cd.png)

**Comment by SystemDisc** [comment]
@elv1n Is this something you're able to fix or would you need someone to submit a PR?

P.S. Thanks so much for maintaining this project. You've done a great job with it!

**Comment by amit-coditas** [comment]
+1 the other slack theme repo is just dead with no PR's merged. All threads is the only issue i see here 👍

**Comment by eyaleizenberg** [comment]
@elv1n Also wanted to say thanks for this. And yes, also noticed that All Threads is not styled.

**Comment by ChintanRaval** [comment]
@elv1n Thanks for the release `0.2.0` and all the awesome work before that. It does fix _most_ of 'All Threads' and (I think) _all_ of 'All Unreads' 🎉 

However, in 'All Threads', any new/unread messages still show up the old way i.e. they show up unstyled just as in pre `0.2.0` release. So I guess this issue now just becomes.. 

> "All Threads" not fully styled

_P.S.: I couldn't wait for `npx install-dark-theme` to work with the new release so got around by manually referencing [`0.2.0` css](https://unpkg.com/install-dark-theme@0.2.0/theme.css) in `ssb-interop.js`_

**Comment by elv1n** [comment]
@eyaleizenberg @amit-coditas @SystemDisc New version with fixes just released

Sorry for the delay, I noticed a few days ago but didn't have enough time. I've added Development section, maybe it will help next time in such cases :)

**Comment by elv1n** [comment]
@ChintanRaval Right, https://unpkg.com use cache and needs time to reset it.
I'm trying another way to publish If it didn't help let's use another resource then unpkg

**Comment by eyaleizenberg** [comment]
Looks great @elv1n ! Thank you!

@ChintanRaval why not get the raw straight from github?

**Comment by elv1n** [comment]
@SystemDisc Do you have unstyled layout at "All threads" now? I wasn't able to reproduce it and not sure if it fixed with latest changes
