### ISSUE TITLE
Slack 4: Cannot get access to /Applications/Slack.app/Contents/resources/app.asar.unpacked/src/static/ssb-interop.js

### ISSUE THREAD

**Issue by jjcodestuff** [elv1n/slack-dark-mojave-theme#7]
Using the newly-released Slack version 4.0.0-beta2 HEAD/e510bc6, when runnning 'npx install-dark-theme' (and sudo...) I get the error: 

> Cannot get access to /Applications/Slack.app/Contents/resources/app.asar.unpacked/src/static/ssb-interop.js

<img width="884" alt="image" src="https://user-images.githubusercontent.com/25162293/59872177-3284f680-9367-11e9-97da-695265d22fbc.png">

**Comment by AMGMNPLK** [comment]
I think it is because Slack could be installed in another directory. Try with: /snap/slack/current/usr/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js

**Comment by jjcodestuff** [comment]
What do you mean, "Try with /snap/slack..."?

**Comment by AMGMNPLK** [comment]
The file is in this directory. I'm very new in Linux, but I have searched for the /usr/lib... and I don't have it there, but in /snap/slack...

**Comment by elv1n** [comment]
Unfortunately, theming for slack could be impossible from 4 versions.
They changed the way how it works and everything now in [app.asar file](https://github.com/electron/asar) and to make any additional.

It possibly can be unpacked, theme injected and pack again but I'm not sure if it's going to work and sounds like a lot of tricks to do.


Let's see, slack mobile have dark theme and I hope they will bring it into the desktop client too and we won't need to use hacks to have a dark theme

**Comment by SpudsMcCat** [comment]
They seem to have removes almost all the js files
(bash shell on Windows to explain the oddball formatting)
/mnt/c/Users/david/AppData/Local/slack/app-4.0.0$ find ./ -name "*js"
./resources/app.asar.unpacked/dist/static/extensions/react-devtools/build/backend.js
./resources/app.asar.unpacked/dist/static/extensions/react-devtools/build/background.js
./resources/app.asar.unpacked/dist/static/extensions/react-devtools/build/contentScript.js
./resources/app.asar.unpacked/dist/static/extensions/react-devtools/build/inject.js
./resources/app.asar.unpacked/dist/static/extensions/react-devtools/build/main.js
./resources/app.asar.unpacked/dist/static/extensions/react-devtools/build/panel.js
./resources/app.asar.unpacked/dist/static/extensions/react-devtools/popups/shared.js
Dowdle-Desktop:/mnt/c/Users/david/AppData/Local/slack/app-4.0.0$

**Comment by LanikSJ** [comment]
See this post: https://gist.github.com/a7madgamal/c2ce04dde8520f426005e5ed28da8608#gistcomment-2968756 for a possible solution.

**Comment by SystemDisc** [comment]
Here's the solution: https://github.com/LanikSJ/slack-dark-mode/compare/master...slack-4.0

```bash
  # Unpack Asar Archive for Slack
  sudo npx asar extract $SLACK_RESOURCES_DIR/app.asar $SLACK_RESOURCES_DIR/app.asar.unpacked

  # Add JS Code to Slack
  sudo tee -a "$SLACK_FILEPATH" < $SLACK_EVENT_LISTENER

  # Insert the CSS File Location in JS
  sudo sed -i -e s@SLACK_DARK_THEME_PATH@$THEME_FILEPATH@g $SLACK_FILEPATH

  # Pack the Asar Archive for Slack
  sudo npx asar pack $SLACK_RESOURCES_DIR/app.asar.unpacked $SLACK_RESOURCES_DIR/app.asar
```

**Comment by tnesavich** [comment]
@SystemDisc 

I am seeing issues with this solution where the npx call is failing with the message below:

sudo npx asar pack $SLACK_RESOURCES_DIR/app.asar.unpacked $SLACK_RESOURCES_DIR/app.asar
Password:
npx: installed 21 in 2.681s
Unexpected token function

**Comment by paul-arthurthiery** [comment]
Hey, the guys at slack-dark-mode seem to have updated their theme injector to work with 4.0 https://gist.github.com/a7madgamal/c2ce04dde8520f426005e5ed28da8608#gistcomment-2971235, might wanna have a look at that

**Comment by jonstuebe** [comment]
They also updated the css classes in 4.0 so it ruins most themes. 😭 

This is what I got to get it working on mac (minus fixing the actual css):

`npm i -g asar`

`asar extract /Applications/Slack.app/Contents/Resources/app.asar /Applications/Slack.app/Contents/Resources/app.asar.unpacked`

`echo '\ndocument.addEventListener("DOMContentLoaded",function(){fetch("https://dark-theme.netlify.com").then(function(e){e.text().then(function(e){const t=document.createElement("style");t.innerText=e,document.head.appendChild(t)})})});' >> /Applications/Slack.app/Contents/Resources/app.asar.unpacked/dist/ssb-interop.bundle.js`

`asar pack /Applications/Slack.app/Contents/Resources/app.asar.unpacked /Applications/Slack.app/Contents/Resources/app.asar`

then restart slack.

Just gotta get that css updated!

**Comment by elv1n** [comment]
Awesome! I will take a look at it and let’s see how much class names they've changed

**Comment by elv1n** [comment]
@jonstuebe Could you confirm that packing/extracting working with Slack 4 beta?

I’m running 
```
asar extract app.asar app.asar.unpacked
asar pack app.asar.unpacked app.asar
```

and then cannot run the slack and have error `“Slack” is damaged and can’t be opened. You should move it to the Trash.`

**Comment by paul-arthurthiery** [comment]
@elv1n not sure if it's related, but Slack 4 is out of beta, you might wanna try with the production version

**Comment by elv1n** [comment]
Yep, the issue happened only for Beta.
Thanks everyone, now `npx install-dark-theme` works for Slack 4 🎉
