### ISSUE TITLE
Theme not applied to "All Unreads" and "Threads"

### ISSUE THREAD

**Issue by JasonCromer** [elv1n/slack-dark-mojave-theme#9]
These two channels are completely un-styled. Repro of https://github.com/elv1n/slack-dark-mojave-theme/issues/4

**Comment by elv1n** [comment]
"All Unreads" styled now
but "Threads" looks correct, can you provide a screenshot and your slack version?

**Comment by mciasuen** [comment]
"Threads" looks fine to me, but "All Unreads" is broken.  I just (~5 minutes ago) quit slack, cleared the cache, rolled back and reinstalled the theme via npx, and restarted it.

Slack version **v4.0.0 (Production)**

Still looks like this:
![Screen Shot 2019-07-25 at 11 22 55](https://user-images.githubusercontent.com/43009667/61887685-16c5c080-aed0-11e9-85e0-ebe28c174cc4.png)

**Comment by elv1n** [comment]
Aha, the problem with an empty page. Thanks, fixed

To get latest changes you need just reload the page :)
